blank_issues_enabled: false
contact_links:
  - name: Feature Request | 特性请求
    url: https://github.com/linuxdeepin/developer-center/discussions/new?category=features-request-ideas-%E7%89%B9%E6%80%A7%E8%AF%B7%E6%B1%82-%E5%A4%B4%E8%84%91%E9%A3%8E%E6%9A%B4
    about: Please create feature requests to the discussion board in our developer-center repo.
  - name: Troubleshooting | 故障排查
    url: https://github.com/linuxdeepin/developer-center/discussions/categories/troubleshooting-%E6%95%85%E9%9A%9C%E6%8E%92%E6%9F%A5
    about: Something does not work but not sure if it is a bug? Report here.
  - name: General Discussion & Questions | 常规讨论与问答
    url: https://github.com/linuxdeepin/developer-center/discussions/categories/q-a-%E9%97%AE%E7%AD%94%E6%9D%BF%E5%9D%97
    about: Please use the discussion board in our developer-center repo.
