---
name: Document Problem Report | 文档问题报告
description: Document Problem Report
body:
- type: textarea
  attributes:
    label: SUMMARY | 问题概要
    description: |
      describe the problem you want to report
      在这里描述你遇到的文档方面的问题
