---
name: Unit Test Report | 单元测试报告
description: Unit Test Report
body:
- type: textarea
  attributes:
    label: SUMMARY | 问题概要
    description: |
      describe the problem you want to report
      在这里描述你遇到的单元测试问题

- type: textarea
  attributes:
    label: PATH | 单元测试文件路径
    description: |
      specify the unit test file path
      遇到问题的单元测试文件路径

- type: textarea
  attributes:
    label: INTERFACE | 测试接口
    description: |
      specify the test interface
      单元测试测试的接口
