#!/bin/bash
display_daemon="/usr/lib/deepin-daemon/greeter-display-daemon"
if [ -x $display_daemon ]; then
    $display_daemon &
fi

export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_INTEGRATION_SHELL=kwayland-shell
export XDG_DATA_DIRS=/usr/share
export XDG_CURRENT_DESKTOP=DDE

/usr/bin/deepin-kwin_wayland_wrapper --xwayland --drm --no-lockscreen /usr/bin/lightdm-deepin-greeter
